
spring:
  datasource:
    url: jdbc:h2:mem:rsupport
    username: rsupport
    password: rsupport12!@
    hikari:
      maximum-pool-size: 4
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:database/data.sql
      mode: always
      platform: h2
  data:
    redis:
      host: localhost
      port: 6379
      password: ""